### PR TITLE
Bump all eclipse plugins to 17

### PR DESCRIPTION
**Pull request by Michael-Baylis**
Signed-off-by: Michael Baylis <Michael.Baylis@uk.ibm.com>

### CODE REVIEW

**Comment by Michael-Baylis** [comment]
rerun tests

**Comment by cicsdeliverytest** [comment]
Build triggered for merge commit.

**Comment by cicsdeliverytest** [comment]
Build started for merge commit.

**Comment by cicsdeliverytest** [comment]
Build triggered for merge commit.

**Comment by cicsdeliverytest** [comment]
Build started for merge commit.

**Comment by cicsdeliverytest** [comment]
Success

**Comment by Michael-Baylis** [comment]
rerun tests

**Comment by Michael-Baylis** [comment]
rerun tests

**Pull request merged**
