### PR TITLE
Bump to version 0.30.0

### PR DESCRIPTION
**Pull request by techcobweb**
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-eclipse-pr-51-ms4nh for details. If you are unable to do so, please contact a member of the Galasa team.

**Review by AaronJhaj — APPROVED** [review]

**Comment by techcobweb** [comment]
Build failing due to this: 
```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for dev.galasa:dev.galasa.simbank.ui:0.29.0: Could not find artifact dev.galasa:galasa-eclipse-parent:pom:0.29.0 in galasa.source.repo (https://repo.maven.apache.org/maven2/) and 'parent.relativePath' points at wrong local POM @ line 6, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for dev.galasa:dev.galasa.simbank.ui:0.29.0: Could not find artifact dev.galasa:galasa-eclipse-parent:pom:0.29.0 in galasa.source.repo (https://repo.maven.apache.org/maven2/) and 'parent.relativePath' points at wrong local POM @ line 6, column 10

    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:397](http://defaultprojectbuilder.java:397/))
    at org.apache.maven.graph.DefaultGraphBuilder.collectProjects ([DefaultGraphBuilder.java:414](http://defaultgraphbuilder.java:414/))
    at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor ([DefaultGraphBuilder.java:405](http://defaultgraphbuilder.java:405/))
    at [org.apache.maven.graph.DefaultGraphBuilder.build](http://org.apache.maven.graph.defaultgraphbuilder.build/) ([DefaultGraphBuilder.java:82](http://defaultgraphbuilder.java:82/))
    at org.apache.maven.DefaultMaven.buildGraph ([DefaultMaven.java:534](http://defaultmaven.java:534/))
    at org.apache.maven.DefaultMaven.doExecute ([DefaultMaven.java:219](http://defaultmaven.java:219/))
    at org.apache.maven.DefaultMaven.doExecute ([DefaultMaven.java:192](http://defaultmaven.java:192/))
    at org.apache.maven.DefaultMaven.execute ([DefaultMaven.java:105](http://defaultmaven.java:105/))
    at org.apache.maven.cli.MavenCli.execute ([MavenCli.java:960](http://mavencli.java:960/))
    at org.apache.maven.cli.MavenCli.doMain ([MavenCli.java:293](http://mavencli.java:293/))
    at org.apache.maven.cli.MavenCli.main ([MavenCli.java:196](http://mavencli.java:196/))
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([NativeMethodAccessorImpl.java:77](http://nativemethodaccessorimpl.java:77/))
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([DelegatingMethodAccessorImpl.java:43](http://delegatingmethodaccessorimpl.java:43/))
    at java.lang.reflect.Method.invoke ([Method.java:568](http://method.java:568/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced ([Launcher.java:282](http://launcher.java:282/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch ([Launcher.java:225](http://launcher.java:225/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode ([Launcher.java:406](http://launcher.java:406/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.main ([Launcher.java:347](http://launcher.java:347/))
[ERROR]   
[ERROR]   The project dev.galasa:dev.galasa.simbank.ui:0.29.0 (/workspace/git/repo-eclipse-pr-51-ms4nh/eclipse/galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for dev.galasa:dev.galasa.simbank.ui:0.29.0: Could not find artifact dev.galasa:galasa-eclipse-parent:pom:0.29.0 in galasa.source.repo (https://repo.maven.apache.org/maven2/) and 'parent.relativePath' points at wrong local POM @ line 6, column 10 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact dev.galasa:galasa-eclipse-parent:pom:0.29.0 in galasa.source.repo (https://repo.maven.apache.org/maven2/)
    at org.apache.maven.project.ProjectModelResolver.resolveModel ([ProjectModelResolver.java:196](http://projectmodelresolver.java:196/))
    at org.apache.maven.project.ProjectModelResolver.resolveModel ([ProjectModelResolver.java:242](http://projectmodelresolver.java:242/))
    at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally ([DefaultModelBuilder.java:1150](http://defaultmodelbuilder.java:1150/))
    at org.apache.maven.model.building.DefaultModelBuilder.readParent ([DefaultModelBuilder.java:916](http://defaultmodelbuilder.java:916/))
    at [org.apache.maven.model.building.DefaultModelBuilder.build](http://org.apache.maven.model.building.defaultmodelbuilder.build/) ([DefaultModelBuilder.java:361](http://defaultmodelbuilder.java:361/))
    at [org.apache.maven.model.building.DefaultModelBuilder.build](http://org.apache.maven.model.building.defaultmodelbuilder.build/) ([DefaultModelBuilder.java:267](http://defaultmodelbuilder.java:267/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:448](http://defaultprojectbuilder.java:448/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:414](http://defaultprojectbuilder.java:414/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:558](http://defaultprojectbuilder.java:558/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:414](http://defaultprojectbuilder.java:414/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:377](http://defaultprojectbuilder.java:377/))
    at org.apache.maven.graph.DefaultGraphBuilder.collectProjects ([DefaultGraphBuilder.java:414](http://defaultgraphbuilder.java:414/))
    at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor ([DefaultGraphBuilder.java:405](http://defaultgraphbuilder.java:405/))
    at [org.apache.maven.graph.DefaultGraphBuilder.build](http://org.apache.maven.graph.defaultgraphbuilder.build/) ([DefaultGraphBuilder.java:82](http://defaultgraphbuilder.java:82/))
    at org.apache.maven.DefaultMaven.buildGraph ([DefaultMaven.java:534](http://defaultmaven.java:534/))
    at org.apache.maven.DefaultMaven.doExecute ([DefaultMaven.java:219](http://defaultmaven.java:219/))
    at org.apache.maven.DefaultMaven.doExecute ([DefaultMaven.java:192](http://defaultmaven.java:192/))
    at org.apache.maven.DefaultMaven.execute ([DefaultMaven.java:105](http://defaultmaven.java:105/))
    at org.apache.maven.cli.MavenCli.execute ([MavenCli.java:960](http://mavencli.java:960/))
    at org.apache.maven.cli.MavenCli.doMain ([MavenCli.java:293](http://mavencli.java:293/))
    at org.apache.maven.cli.MavenCli.main ([MavenCli.java:196](http://mavencli.java:196/))
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([NativeMethodAccessorImpl.java:77](http://nativemethodaccessorimpl.java:77/))
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([DelegatingMethodAccessorImpl.java:43](http://delegatingmethodaccessorimpl.java:43/))
    at java.lang.reflect.Method.invoke ([Method.java:568](http://method.java:568/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced ([Launcher.java:282](http://launcher.java:282/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch ([Launcher.java:225](http://launcher.java:225/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode ([Launcher.java:406](http://launcher.java:406/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.main ([Launcher.java:347](http://launcher.java:347/))
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact dev.galasa:galasa-eclipse-parent:pom:0.29.0 in galasa.source.repo (https://repo.maven.apache.org/maven2/)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve ([DefaultArtifactResolver.java:425](http://defaultartifactresolver.java:425/))
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts ([DefaultArtifactResolver.java:229](http://defaultartifactresolver.java:229/))
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact ([DefaultArtifactResolver.java:207](http://defaultartifactresolver.java:207/))
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact ([DefaultRepositorySystem.java:262](http://defaultrepositorysystem.java:262/))
    at org.apache.maven.project.ProjectModelResolver.resolveModel ([ProjectModelResolver.java:192](http://projectmodelresolver.java:192/))
    at org.apache.maven.project.ProjectModelResolver.resolveModel ([ProjectModelResolver.java:242](http://projectmodelresolver.java:242/))
    at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally ([DefaultModelBuilder.java:1150](http://defaultmodelbuilder.java:1150/))
    at org.apache.maven.model.building.DefaultModelBuilder.readParent ([DefaultModelBuilder.java:916](http://defaultmodelbuilder.java:916/))
    at [org.apache.maven.model.building.DefaultModelBuilder.build](http://org.apache.maven.model.building.defaultmodelbuilder.build/) ([DefaultModelBuilder.java:361](http://defaultmodelbuilder.java:361/))
    at [org.apache.maven.model.building.DefaultModelBuilder.build](http://org.apache.maven.model.building.defaultmodelbuilder.build/) ([DefaultModelBuilder.java:267](http://defaultmodelbuilder.java:267/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:448](http://defaultprojectbuilder.java:448/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:414](http://defaultprojectbuilder.java:414/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:558](http://defaultprojectbuilder.java:558/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:414](http://defaultprojectbuilder.java:414/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:377](http://defaultprojectbuilder.java:377/))
    at org.apache.maven.graph.DefaultGraphBuilder.collectProjects ([DefaultGraphBuilder.java:414](http://defaultgraphbuilder.java:414/))
    at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor ([DefaultGraphBuilder.java:405](http://defaultgraphbuilder.java:405/))
    at [org.apache.maven.graph.DefaultGraphBuilder.build](http://org.apache.maven.graph.defaultgraphbuilder.build/) ([DefaultGraphBuilder.java:82](http://defaultgraphbuilder.java:82/))
    at org.apache.maven.DefaultMaven.buildGraph ([DefaultMaven.java:534](http://defaultmaven.java:534/))
    at org.apache.maven.DefaultMaven.doExecute ([DefaultMaven.java:219](http://defaultmaven.java:219/))
    at org.apache.maven.DefaultMaven.doExecute ([DefaultMaven.java:192](http://defaultmaven.java:192/))
    at org.apache.maven.DefaultMaven.execute ([DefaultMaven.java:105](http://defaultmaven.java:105/))
    at org.apache.maven.cli.MavenCli.execute ([MavenCli.java:960](http://mavencli.java:960/))
    at org.apache.maven.cli.MavenCli.doMain ([MavenCli.java:293](http://mavencli.java:293/))
    at org.apache.maven.cli.MavenCli.main ([MavenCli.java:196](http://mavencli.java:196/))
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([NativeMethodAccessorImpl.java:77](http://nativemethodaccessorimpl.java:77/))
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([DelegatingMethodAccessorImpl.java:43](http://delegatingmethodaccessorimpl.java:43/))
    at java.lang.reflect.Method.invoke ([Method.java:568](http://method.java:568/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced ([Launcher.java:282](http://launcher.java:282/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch ([Launcher.java:225](http://launcher.java:225/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode ([Launcher.java:406](http://launcher.java:406/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.main ([Launcher.java:347](http://launcher.java:347/))
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact dev.galasa:galasa-eclipse-parent:pom:0.29.0 in galasa.source.repo (https://repo.maven.apache.org/maven2/)
    at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed ([ArtifactTransportListener.java:48](http://artifacttransportlistener.java:48/))
    at [org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run](http://org.eclipse.aether.connector.basic.basicrepositoryconnector%24taskrunner.run/) ([BasicRepositoryConnector.java:369](http://basicrepositoryconnector.java:369/))
    at [org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run](http://org.eclipse.aether.util.concurrency.runnableerrorforwarder%241.run/) ([RunnableErrorForwarder.java:75](http://runnableerrorforwarder.java:75/))
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute ([BasicRepositoryConnector.java:628](http://basicrepositoryconnector.java:628/))
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get ([BasicRepositoryConnector.java:262](http://basicrepositoryconnector.java:262/))
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads ([DefaultArtifactResolver.java:514](http://defaultartifactresolver.java:514/))
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve ([DefaultArtifactResolver.java:402](http://defaultartifactresolver.java:402/))
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts ([DefaultArtifactResolver.java:229](http://defaultartifactresolver.java:229/))
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact ([DefaultArtifactResolver.java:207](http://defaultartifactresolver.java:207/))
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact ([DefaultRepositorySystem.java:262](http://defaultrepositorysystem.java:262/))
    at org.apache.maven.project.ProjectModelResolver.resolveModel ([ProjectModelResolver.java:192](http://projectmodelresolver.java:192/))
    at org.apache.maven.project.ProjectModelResolver.resolveModel ([ProjectModelResolver.java:242](http://projectmodelresolver.java:242/))
    at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally ([DefaultModelBuilder.java:1150](http://defaultmodelbuilder.java:1150/))
    at org.apache.maven.model.building.DefaultModelBuilder.readParent ([DefaultModelBuilder.java:916](http://defaultmodelbuilder.java:916/))
    at [org.apache.maven.model.building.DefaultModelBuilder.build](http://org.apache.maven.model.building.defaultmodelbuilder.build/) ([DefaultModelBuilder.java:361](http://defaultmodelbuilder.java:361/))
    at [org.apache.maven.model.building.DefaultModelBuilder.build](http://org.apache.maven.model.building.defaultmodelbuilder.build/) ([DefaultModelBuilder.java:267](http://defaultmodelbuilder.java:267/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:448](http://defaultprojectbuilder.java:448/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:414](http://defaultprojectbuilder.java:414/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:558](http://defaultprojectbuilder.java:558/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:414](http://defaultprojectbuilder.java:414/))
    at [org.apache.maven.project.DefaultProjectBuilder.build](http://org.apache.maven.project.defaultprojectbuilder.build/) ([DefaultProjectBuilder.java:377](http://defaultprojectbuilder.java:377/))
    at org.apache.maven.graph.DefaultGraphBuilder.collectProjects ([DefaultGraphBuilder.java:414](http://defaultgraphbuilder.java:414/))
    at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor ([DefaultGraphBuilder.java:405](http://defaultgraphbuilder.java:405/))
    at [org.apache.maven.graph.DefaultGraphBuilder.build](http://org.apache.maven.graph.defaultgraphbuilder.build/) ([DefaultGraphBuilder.java:82](http://defaultgraphbuilder.java:82/))
    at org.apache.maven.DefaultMaven.buildGraph ([DefaultMaven.java:534](http://defaultmaven.java:534/))
    at org.apache.maven.DefaultMaven.doExecute ([DefaultMaven.java:219](http://defaultmaven.java:219/))
    at org.apache.maven.DefaultMaven.doExecute ([DefaultMaven.java:192](http://defaultmaven.java:192/))
    at org.apache.maven.DefaultMaven.execute ([DefaultMaven.java:105](http://defaultmaven.java:105/))
    at org.apache.maven.cli.MavenCli.execute ([MavenCli.java:960](http://mavencli.java:960/))
    at org.apache.maven.cli.MavenCli.doMain ([MavenCli.java:293](http://mavencli.java:293/))
    at org.apache.maven.cli.MavenCli.main ([MavenCli.java:196](http://mavencli.java:196/))
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([NativeMethodAccessorImpl.java:77](http://nativemethodaccessorimpl.java:77/))
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([DelegatingMethodAccessorImpl.java:43](http://delegatingmethodaccessorimpl.java:43/))
    at java.lang.reflect.Method.invoke ([Method.java:568](http://method.java:568/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced ([Launcher.java:282](http://launcher.java:282/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch ([Launcher.java:225](http://launcher.java:225/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode ([Launcher.java:406](http://launcher.java:406/))
    at org.codehaus.plexus.classworlds.launcher.Launcher.main ([Launcher.java:347](http://launcher.java:347/))
```

**Comment by AaronJhaj** [comment]
did you bump these files up ? 

    - galasa-eclipse-parent/dev.galasa.simbank.ui/META-INF/MANIFEST.MF

    - galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
