### PR TITLE
bump commons.lang to 3.12

### PR DESCRIPTION
**Pull request by AaronJhaj**
Signed-off-by: Aaron Jhaj <Aaron.Jhaj@ibm.com>

### CODE REVIEW

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-eclipse-pr-39-q4ff6 for details

**Review by eamansour — APPROVED** [review]

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-eclipse-pr-39-bvvvc for details

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-eclipse-pr-39-pqgvx for details

**Comment by galasa-team** [comment]
Build failed, see https://tekton.galasa.dev/#/namespaces/galasa-pipelines/pipelineruns/repo-eclipse-pr-39-7nnrt for details

**Comment by galasa-team** [comment]
Build successful

**Pull request merged**
